from typing import TypedDict, List, Optional, Dict, Any, Tuple
from langgraph.graph import END, StateGraph, START

# --- 1. Define Graph State ---
# The state is a dictionary that flows through the graph.
# Each node reads this state and writes its results to it.

class GraphState(TypedDict):
    """
    Represents the state of our RAG graph.

    Attributes:
        question: The user's input question.
        reference_answer: The reference answer for benchmarking.
        retrieved_context: The documents retrieved by the RAG node (list of tuples with (content, metadata)).
        prompt: The final prompt sent to the LLM.
        generation: The raw output from the 'Main LLM'.
        final_answer: The answer validated by the 'Logic Checker'.
        error_detected: Boolean indicating if the 'Logic Checker' found an error.
        error_count: Counter to prevent infinite loops.
        grade: The result from the 'Answer Grader'.
        benchmark_results: The final score from the 'Benchmark'.
    """
    question: str
    reference_answer: str
    retrieved_context: List[Tuple[str, Dict[str, Any]]] # List of documents with metadata
    prompt: str
    generation: str
    final_answer: Optional[str]
    error_detected: bool
    error_count: int
    grade: Optional[Dict[str, Any]]

class BenchmarkState(TypedDict):
    """
    Represents the state for benchmarking multiple Q/A pairs.

    Attributes:
        qa_pairs: List of (question, reference_answer) pairs.
        grades: List of grading results for each Q/A pair.
        benchmark_results: Aggregated results from the benchmark.
        sub_rag_system: The sub-graph handling individual Q/A processing.
    """
    qa_pairs: List[Tuple[str, str]]
    grades: List[Dict[str, Any]]
    benchmark_results: Dict[str, Any]
    sub_rag_system: StateGraph


# --- 2. Define Graph Nodes ---
# Each node is a function that takes the state as input
# and returns a dictionary containing the state keys to update.

def retrieve_documents(state: GraphState) -> GraphState:
    """
    Node: 'Retrieval Augmented Generation (RAG)'
    Takes the 'question' from the state and retrieves relevant context.
    (Implies the 'Parser' and 'Data Base' steps upstream).
    """
    print("--- NODE: Retrieve Documents ---")
    question = state["question"]
    
    # ... Your Retriever logic (e.g., BM25, ChromaDB, etc.) ...
    # retriever = ...
    # documents = retriever.invoke(question)

    retrieved_context = [("Fictional context 1", {}), ("Fictional context 2", {})] # Placeholder
    
    return {"retrieved_context": retrieved_context}

def engineer_prompt(state: GraphState) -> GraphState:
    """
    Node: 'Engineered Prompt'
    Builds the final prompt using the question and the retrieved context.
    Also accounts for past errors if in a correction loop.
    """
    print("--- NODE: Engineer Prompt ---")
    question = state["question"]
    context = state["retrieved_context"]
    
    # ... Your prompt formatting logic ...
    # template = f"Question: {question}\nContext: {context}\nAnswer:"
    
    prompt = f"Formatted prompt for question: {question}" # Placeholder
    
    return {"prompt": prompt}

def generate_answer(state: GraphState) -> GraphState:
    """
    Node: 'Main LLM'
    Calls the main language model with the prompt.
    """
    print("--- NODE: Generate Answer (Main LLM) ---")
    prompt = state["prompt"]
    
    # ... Your LLM call logic ...
    # llm = ...
    # generation = llm.invoke(prompt)
    
    generation = "Fictional answer generated by the LLM." # Placeholder
    
    return {"generation": generation}

def check_logic(state: GraphState) -> GraphState:
    """
    Node: 'Logic Checker'
    Verifies the LLM's generation. If an error is found, it flags it.
    Otherwise, it validates the 'final_answer'.
    """
    print("--- NODE: Check Logic ---")
    generation = state["generation"]
    error_count = state.get("error_count", 0)
    
    # ... Your verification logic (e.g., call another LLM, regex, etc.) ...
    
    if "error" in generation.lower(): # Placeholder error detection logic
        print("    -> Error detected. Incrementing counter.")
        return {
            "error_detected": True,
            "error_count": error_count + 1
        }
    else:
        print("    -> No error detected. Validating answer.")
        return {
            "error_detected": False,
            "final_answer": generation # The generation is validated
        }

def grade_answer(state: GraphState) -> GraphState:
    """
    Node: 'Answer Grader'
    Compares the 'final_answer' with the 'reference_answer' to produce a score.
    """
    print("--- NODE: Grade Answer ---")
    final_answer = state["final_answer"]
    reference_answer = state["reference_answer"]
    
    # ... Your grading logic (e.g., call a "judge" LLM, ROUGE score, etc.) ...
    
    grade = {"score": 0.9, "reasoning": "The answer is relevant."} # Placeholder
    
    return {"grade": grade}

def run_qa_pairs(state: BenchmarkState) -> BenchmarkState:
    """
    Node: 'Run Q/A Pairs'
    Executes the sub-graph for each Q/A pair and collects grades.
    """
    print("--- NODE: Run Q/A Pairs ---")
    qa_pairs = state["qa_pairs"]
    sub_rag_system = state["sub_rag_system"]
    
    grades = []
    
    for question, reference_answer in qa_pairs:
        print(f"    -> Processing Q/A pair: {question} / {reference_answer}")
        # Initialize state for the sub-graph
        sub_state: GraphState = {
            "question": question,
            "reference_answer": reference_answer,
            "retrieved_context": [],
            "prompt": "",
            "generation": "",
            "final_answer": None,
            "error_detected": False,
            "error_count": 0,
            "grade": None
        }
        
        app = sub_rag_system.compile()
        
        # Execute the sub-graph
        final_state = app.invoke(sub_state)

        # Collect the grade
        grades.append(final_state["grade"])
    
    return {"grades": grades}

def run_benchmark(state: BenchmarkState) -> BenchmarkState:
    """
    Node: 'Benchmark'
    Aggregates grades from multiple Q/A pairs into benchmark results.
    """
    print("--- NODE: Benchmark ---")
    grades = state["grades"]
    
    # ... Your benchmark aggregation logic ...

    benchmark_results = {"average_score": sum(grade["score"] for grade in grades)
                         / len(grades)} # Placeholder

    return {"benchmark_results": benchmark_results}


# --- 3. Define Conditional Edges ---

def decide_after_logic_check(state: GraphState) -> str:
    """
    Decision Point: After 'Logic Checker'
    Determines the next step after the logic check.
    - 'if error detected': Returns to 'engineer_prompt' (loop).
    - 'else': Continues to 'grade_answer' (and 'Final Answer' is implicit).
    """
    print("--- DECISION: After Logic Check ---")
    MAX_RETRIES = 2
    
    if state["error_detected"] and state["error_count"] < MAX_RETRIES:
        print("    -> Route: 're-prompt' (loop)")
        return "reprompt"
    else:
        if state["error_detected"]:
            print("    -> Route: 'grade_answer' (retry limit reached)")
        else:
            print("    -> Route: 'grade_answer' (answer validated)")
        return "proceed"

# --- 4. Assemble the Graph ---

def build_single_qa_graph() -> StateGraph:
    """
    Builds a simplified graph for single Q/A without benchmarking.
    """

    # Initialize the graph
    workflow = StateGraph(GraphState)

    # Add nodes to the graph
    workflow.add_node("retrieve_documents", retrieve_documents)
    workflow.add_node("engineer_prompt", engineer_prompt)
    workflow.add_node("generate_answer", generate_answer)
    workflow.add_node("check_logic", check_logic)
    workflow.add_node("grade_answer", grade_answer)

    # Define the entry point
    # The flow starts with document retrieval
    workflow.add_edge(START, "retrieve_documents")

    # Add edges (connections)
    workflow.add_edge("retrieve_documents", "engineer_prompt")
    workflow.add_edge("engineer_prompt", "generate_answer")
    workflow.add_edge("generate_answer", "check_logic")

    # Add the conditional edge
    workflow.add_conditional_edges(
        "check_logic",  # Source node
        decide_after_logic_check, # Decision function
        {
            # 'if error detected' (route name) -> 'engineer_prompt' (target node)
            "reprompt": "engineer_prompt",
            # 'else' (route name) -> 'grade_answer' (target node)
            "proceed": "grade_answer"
        }
    )

    # The 'Grader' is the end of the flow
    workflow.add_edge("grade_answer", END)

    return workflow

def build_full_benchmark_graph() -> StateGraph:
    """
    Builds the complete RAG graph with all nodes and edges.
    """

    # Initialize the graph
    workflow = StateGraph(BenchmarkState)

    # Add nodes to the graph
    workflow.add_node("run_qa_pairs", run_qa_pairs)
    workflow.add_node("benchmark", run_benchmark)

    # Define the entry point
    workflow.add_edge(START, "run_qa_pairs")

    # Add edges (connections)
    workflow.add_edge("run_qa_pairs", "benchmark")
    workflow.add_edge("benchmark", END)

    return workflow



# --- 5. Compile and Run ---

if __name__ == "__main__":
    # Build the sub-graph for single Q/A processing
    sub_rag_system = build_single_qa_graph()
    
    # Build the full benchmark graph
    workflow = build_full_benchmark_graph()

    # Compile the graph
    app = workflow.compile()
    
    # Inject the sub-graph into the benchmark graph's initial state
    inputs = {
        "qa_pairs": [
            ("What is the capital of France?", "Paris is the capital of France."),
            ("Who wrote '1984'?", "'1984' was written by George Orwell."),
            ("List the primary colors.", "The primary colors are red, blue, and yellow.")
        ],
        "sub_rag_system": sub_rag_system
    }
    
    # Execute the graph
    print("--- STARTING GRAPH EXECUTION ---")

    final_state = app.invoke(inputs)
    print(final_state["benchmark_results"])
    
    print("--- END OF EXECUTION ---")