import operator
from typing import TypedDict, List, Optional, Dict, Any, Tuple
from langgraph.graph import StateGraph, END

# --- 1. Define Graph State ---
# The state is a dictionary that flows through the graph.
# Each node reads this state and writes its results to it.

class GraphState(TypedDict):
    """
    Represents the state of our RAG graph.

    Attributes:
        question: The user's input question.
        reference_answer: The reference answer for benchmarking.
        retrieved_context: The documents retrieved by the RAG node (list of tuples with (content, metadata)).
        prompt: The final prompt sent to the LLM.
        generation: The raw output from the 'Main LLM'.
        final_answer: The answer validated by the 'Logic Checker'.
        error_detected: Boolean indicating if the 'Logic Checker' found an error.
        error_count: Counter to prevent infinite loops.
        grade: The result from the 'Answer Grader'.
        benchmark_results: The final score from the 'Benchmark'.
    """
    question: str
    reference_answer: str
    retrieved_context: List[Tuple[str, Dict[str, Any]]] # List of documents with metadata
    prompt: str
    generation: str
    final_answer: Optional[str]
    error_detected: bool
    error_count: int
    grade: Optional[Dict[str, Any]]
    benchmark_results: Optional[Dict[str, Any]]


# --- 2. Define Graph Nodes ---
# Each node is a function that takes the state as input
# and returns a dictionary containing the state keys to update.

def retrieve_documents(state: GraphState) -> GraphState:
    """
    Node: 'Retrieval Augmented Generation (RAG)'
    Takes the 'question' from the state and retrieves relevant context.
    (Implies the 'Parser' and 'Data Base' steps upstream).
    """
    print("--- NODE: Retrieve Documents ---")
    question = state["question"]
    
    # ... Your Retriever logic (e.g., BM25, ChromaDB, etc.) ...
    # retriever = ...
    # documents = retriever.invoke(question)

    retrieved_context = [("Fictional context 1", {}), ("Fictional context 2", {})] # Placeholder
    
    return {"retrieved_context": retrieved_context}

def engineer_prompt(state: GraphState) -> GraphState:
    """
    Node: 'Engineered Prompt'
    Builds the final prompt using the question and the retrieved context.
    Also accounts for past errors if in a correction loop.
    """
    print("--- NODE: Engineer Prompt ---")
    question = state["question"]
    context = state["retrieved_context"]
    
    # ... Your prompt formatting logic ...
    # template = f"Question: {question}\nContext: {context}\nAnswer:"
    
    prompt = f"Formatted prompt for question: {question}" # Placeholder
    
    return {"prompt": prompt}

def generate_answer(state: GraphState) -> GraphState:
    """
    Node: 'Main LLM'
    Calls the main language model with the prompt.
    """
    print("--- NODE: Generate Answer (Main LLM) ---")
    prompt = state["prompt"]
    
    # ... Your LLM call logic ...
    # llm = ...
    # generation = llm.invoke(prompt)
    
    generation = "Fictional answer generated by the LLM." # Placeholder
    
    return {"generation": generation}

def check_logic(state: GraphState) -> GraphState:
    """
    Node: 'Logic Checker'
    Verifies the LLM's generation. If an error is found, it flags it.
    Otherwise, it validates the 'final_answer'.
    """
    print("--- NODE: Check Logic ---")
    generation = state["generation"]
    error_count = state.get("error_count", 0)
    
    # ... Your verification logic (e.g., call another LLM, regex, etc.) ...
    
    if "error" in generation.lower(): # Placeholder error detection logic
        print("    -> Error detected. Incrementing counter.")
        return {
            "error_detected": True,
            "error_count": error_count + 1
        }
    else:
        print("    -> No error detected. Validating answer.")
        return {
            "error_detected": False,
            "final_answer": generation # The generation is validated
        }

def grade_answer(state: GraphState) -> GraphState:
    """
    Node: 'Answer Grader'
    Compares the 'final_answer' with the 'reference_answer' to produce a score.
    """
    print("--- NODE: Grade Answer ---")
    final_answer = state["final_answer"]
    reference_answer = state["reference_answer"]
    
    # ... Your grading logic (e.g., call a "judge" LLM, ROUGE score, etc.) ...
    
    grade = {"score": 0.9, "reasoning": "The answer is relevant."} # Placeholder
    
    return {"grade": grade}

def run_benchmark(state: GraphState) -> GraphState:
    """
    Node: 'Benchmark'
    Aggregates the score. In a real case, this node might aggregate
    scores over multiple Q/A pairs.
    """
    print("--- NODE: Benchmark ---")
    grade = state["grade"]
    
    # ... Your benchmark aggregation logic ...
    
    benchmark_results = {"average_score": grade["score"]} # Placeholder
    
    return {"benchmark_results": benchmark_results}


# --- 3. Define Conditional Edges ---

def decide_after_logic_check(state: GraphState) -> str:
    """
    Decision Point: After 'Logic Checker'
    Determines the next step after the logic check.
    - 'if error detected': Returns to 'engineer_prompt' (loop).
    - 'else': Continues to 'grade_answer' (and 'Final Answer' is implicit).
    """
    print("--- DECISION: After Logic Check ---")
    MAX_RETRIES = 2
    
    if state["error_detected"] and state["error_count"] < MAX_RETRIES:
        print("    -> Route: 're-prompt' (loop)")
        return "reprompt"
    else:
        if state["error_detected"]:
            print("    -> Route: 'grade_answer' (retry limit reached)")
        else:
            print("    -> Route: 'grade_answer' (answer validated)")
        return "proceed"

# --- 4. Assemble the Graph ---

# Initialize the graph
workflow = StateGraph(GraphState)

# Add nodes to the graph
workflow.add_node("retrieve_documents", retrieve_documents)
workflow.add_node("engineer_prompt", engineer_prompt)
workflow.add_node("generate_answer", generate_answer)
workflow.add_node("check_logic", check_logic)
workflow.add_node("grade_answer", grade_answer)
workflow.add_node("run_benchmark", run_benchmark)

# Define the entry point
# The flow starts with document retrieval
workflow.set_entry_point("retrieve_documents")

# Add edges (connections)
workflow.add_edge("retrieve_documents", "engineer_prompt")
workflow.add_edge("engineer_prompt", "generate_answer")
workflow.add_edge("generate_answer", "check_logic")

# Add the conditional edge
workflow.add_conditional_edges(
    "check_logic",  # Source node
    decide_after_logic_check, # Decision function
    {
        # 'if error detected' (route name) -> 'engineer_prompt' (target node)
        "reprompt": "engineer_prompt",
        # 'else' (route name) -> 'grade_answer' (target node)
        "proceed": "grade_answer"
    }
)

# The 'Grader' leads to the 'Benchmark'
workflow.add_edge("grade_answer", "run_benchmark")

# The 'Benchmark' is the end of the flow
workflow.add_edge("run_benchmark", END)


# --- 5. Compile and Run ---

# Compile the graph
app = workflow.compile()

# Define the input (based on 'Challenges Q/A pairs')
inputs = {
    "question": "What is the capital of France?",
    "reference_answer": "Paris is the capital of France."
}

# Execute the graph
print("--- STARTING GRAPH EXECUTION ---")
# Streaming displays the output of each node as it runs
for output in app.stream(inputs, {"recursion_limit": 5}):
    # output is a dictionary of the form {node_name: node_output}
    print(output)
    print("="*30)

print("--- END OF EXECUTION ---")

# You can also retrieve the final complete state
# final_state = app.invoke(inputs, {"recursion_limit": 5})
# print(final_state["benchmark_results"])