"""
Base query transformer interface for query transforming techniques.

This module defines the abstract interface for transforming queries in order to
perform techniques such as RAG fusion or HyDe
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
import agents.prepare_agent as prepare_agent

class BaseQueryTransformer(ABC):
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize the query transformer with configuration.
        
        Args:
            config: query transformer-specific configuration options
                   Common options:
                   - query_transformer_model: Name/path of embedding model
                   - batch_size: Number of chunks to process at once
        """
        self.agent = prepare_agent.prepare_query_transformer_agent()
        self.generated_instances_amount = config.get('query_transformers.amount_of_generated_instances', "several")
        self.rate_limit_delay = config.get('agent.rate_limit_delay', 0)
    
    @abstractmethod
    def transform(self, query: str, verbose: bool = False) -> List[str]:
        """
        Return the result of a call to a LLM in order to transform a query
        
        Args:
            query: Natural language query
            verbose: If True, print the generated questions/summaries
            
        Returns:
            List of strings generated by a LLM depending on the instructions
        """
        pass