from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

class LLMAgent(ABC):
    """Abstract interface for LLM agents"""
    
    @abstractmethod
    def initialize(self) -> None:
        """Initialize the agent with its required configurations"""
        pass
    
    @abstractmethod
    def process_question(self, question: str, context: Optional[List[str]] = None) -> str:
        """Process a question with optional context and return an answer
        
        Args:
            question: The question asked by the user
            context: Optional list of relevant code chunks
            
        Returns:
            str: The response generated by the LLM
        """
        pass
    
    @abstractmethod
    def get_embedding(self, text: str) -> List[float]:
        """Generate an embedding for the given text
        
        Args:
            text: The text to encode
            
        Returns:
            List[float]: The embedding vector
        """
        pass
    
    @abstractmethod
    def extract_metadata(self, code_chunk: str) -> Dict[str, Any]:
        """Extract metadata from a code chunk
        
        Args:
            code_chunk: The code chunk to analyze
            
        Returns:
            Dict[str, Any]: The extracted metadata (functions, variables, etc.)
        """
        pass