from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional, Callable
import time
import functools

def rate_limited(max_retries: int = 5, initial_delay: float = 2.0):
    """Decorator to handle rate limiting and retries for LLM API calls.
    
    Args:
        max_retries: Maximum number of retry attempts
        initial_delay: Initial delay between retries in seconds
    """
    def decorator(func: Callable):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for attempt in range(max_retries):
                try:
                    result = func(*args, **kwargs)
                    # Short pause after successful call
                    time.sleep(0.5)
                    return result
                except Exception as e:
                    error_msg = str(e).lower()
                    if ("rate limit" in error_msg or "quota" in error_msg) and attempt < max_retries - 1:
                        wait_time = initial_delay * (2 ** attempt)
                        print(f"Rate limit hit. Waiting {wait_time} seconds...")
                        time.sleep(wait_time)
                        continue
                    if attempt == max_retries - 1:
                        raise Exception("Failed after multiple retries: " + str(e))
                    raise
        return wrapper
    return decorator

class BaseEmbedder(ABC):
    """Abstract interface for embedding models"""
    
    @abstractmethod
    def embed(self, text: str) -> List[float]:
        """Generate an embedding for a single text"""
        pass
    
    @abstractmethod
    def embed_batch(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for multiple texts"""
        pass
    
    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the embedding dimension"""
        pass
    
    @property
    @abstractmethod
    def model_name(self) -> str:
        """Return the model name for identification"""
        pass

class LLMAgent(ABC):
    """Abstract interface for LLM agents"""
    
    @abstractmethod
    def initialize(self) -> None:
        """Initialize the agent with its required configurations"""
        pass
    
    @abstractmethod
    def process_question(self, question: str, context: Optional[List[str]] = None) -> str:
        """Process a question with optional context and return an answer
        
        Args:
            question: The question asked by the user
            context: Optional list of relevant code chunks
            
        Returns:
            str: The response generated by the LLM
        """
        pass
    
    @abstractmethod
    def get_embedding(self, text: str) -> List[float]:
        """Generate an embedding for the given text
        
        Args:
            text: The text to encode
            
        Returns:
            List[float]: The embedding vector
        """
        pass
    
    @abstractmethod
    def extract_metadata(self, code_chunk: str) -> Dict[str, Any]:
        """Extract metadata from a code chunk
        
        Args:
            code_chunk: The code chunk to analyze
            
        Returns:
            Dict[str, Any]: The extracted metadata (functions, variables, etc.)
        """
        pass