from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional, Tuple
import time
import functools

def rate_limited(max_retries: int = 3, initial_delay: float = 1.0):
    """
    Decorator to handle rate limiting and retries for LLM API calls.
    
    Args:
        max_retries: Maximum number of retry attempts
        initial_delay: Initial delay between retries in seconds
    """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for attempt in range(max_retries):
                try:
                    result = func(*args, **kwargs)
                    # Short pause after successful call
                    time.sleep(0.1)
                    return result
                except Exception as e:
                    error_msg = str(e).lower()
                    if ("rate limit" in error_msg or "quota" in error_msg) and attempt < max_retries - 1:
                        wait_time = initial_delay * (2 ** attempt)
                        print(f"Rate limit hit. Waiting {wait_time:.1f} seconds...")
                        time.sleep(wait_time)
                        continue
                    if attempt == max_retries - 1:
                        raise Exception(f"Failed after {max_retries} retries: {str(e)}")
                    raise
        return wrapper
    return decorator


class LLMAgent(ABC):
    """Abstract interface for LLM agents"""
    
    @abstractmethod
    def initialize(self) -> None:
        """Initialize the agent with its required configurations"""
        pass
    
    @abstractmethod  
    def generate_response(self, question: str, context: Optional[str] = None) -> str:
        """Generate a response to a question with optional context
        
        Args:
            question: The question asked by the user
            context: Optional context to provide to the LLM
            
        Returns:
            str: The response generated by the LLM
        """
        pass
    
    @property
    @abstractmethod
    def extract_metadata(self, code_chunk: str) -> Dict[str, Any]:
        """Extract metadata from a code chunk
        
        Args:
            code_chunk: The code chunk to analyze
            
        Returns:
            Dict[str, Any]: The extracted metadata (functions, variables, etc.)
        """
        pass

class Embedder(ABC):
    """Abstract interface for embedders"""

    @abstractmethod
    def get_embedding(self, text: List[str]):
        """Generate an embedding for the given text
        
        Args:
            text: The text to encode
            
        Returns:
            List[float]: The embedding vector
        """
        pass
    
    @abstractmethod
    def tokenize(self, text: str):
        """Tokenize the given text into a list of tokens

        Args:
            text: The text to tokenize

        Returns:
            List[str]: The list of tokens
        """
        pass

    @abstractmethod
    def embed(self, tokens: List[str]):
        """Embed the given tokens and return a vector representation

        Args:
            tokens: The list of tokens to embed

        Returns:
            List[float]: The vector representation of the embedded tokens
        """
        pass

class RAG(ABC):
    """Abstract interface for Retrieval-Augmented Generation (RAG) systems"""
    
    @abstractmethod
    def initialize(self, parsed_data_base: Any) -> None:
        """Initialize the RAG system with necessary components"""
        pass

    @abstractmethod
    def retrieve(self, query: str, top_k: int = 5) -> List[str]:
        """Retrieve relevant documents or code chunks based on the query
        
        Args:
            query: The input query string
            top_k: The number of top relevant items to retrieve
            
        Returns:
            List[str]: A list of retrieved documents or code chunks
        """
        pass

class PromptConstructor(ABC):
    """Abstract interface for prompt constructors"""
    
    @abstractmethod
    def construct_prompt(self, question: str, context: List[str]) -> str:
        """Construct a prompt for the LLM based on the question and optional context
        
        Args:
            question: The question asked by the user
            context: List of relevant code chunks
            
        Returns:
            str: The constructed prompt
        """
        pass

class LogicChecker(ABC):
    """Abstract interface for logic checkers"""
    
    @abstractmethod
    def check_logic(self, answer: str) -> Tuple[bool, Optional[Dict[str, Any]]]:
        """Check the logical consistency of the given answer
        
        Args:
            answer: The answer to analyze

        Returns:
            Tuple[bool, Optional[Dict[str, Any]]]: A tuple where the first element
            indicates if the answer is logically consistent, and the second element
            provides details if inconsistencies are found
        """
        pass

class AnswerGrader(ABC):
    """Abstract interface for answer graders"""
    
    @abstractmethod
    def grade_answer(self, answer: str, question: Optional[str] = None,
                     reference: Optional[str] = None) -> Dict[str, Any]:
        """Grade the given answer based on the question and optional reference
        
        Args:
            answer: The answer to grade
            question: The question asked by the user (optional)
            reference: Optional reference answer for comparison

        Returns:
            Dict[str, Any]: A dictionary containing grading metrics and feedback
        """
        pass

class Parser(ABC):
    """Abstract interface for parsers"""
    
    @abstractmethod
    def parse(self, raw_data: str) -> Any:
        """Parse raw data into a structured format
        
        Args:
            raw_data: The raw data to parse
            
        Returns:
            Any: The structured representation of the parsed data
        """
    def model_name(self) -> str:
        """Return the model name for identification"""
        pass