import google.generativeai as genai
from typing import Dict, Any, Optional, List
from .base import LLMAgent
import json
import os

class GeminiAgent(LLMAgent):
    def __init__(self):
        """
        Initialize the Gemini agent by retrieving the API key from environment variables.
        
        Raises:
            ValueError: If the API key is missing or invalid
            ConnectionError: If the connection to the API fails
        """
        super().__init__()
        self.api_key = None
        self.model = None
        self.generation_config = {
            "temperature": 0.7,
            "top_p": 0.95,
            "top_k": 40,
            "max_output_tokens": 2048,
        }
        
    def list_available_models(self) -> List[str]:
        """
        Get a list of all available Gemini models.
        
        Returns:
            List[str]: List of model names
            
        Raises:
            ConnectionError: If the connection to the API fails
        """
        try:
            return [model.name for model in genai.list_models()]
        except Exception as e:
            raise ConnectionError(f"Failed to retrieve models list: {str(e)}")

    def initialize(self) -> None:
        """
        Initialize the connection to the Gemini API.
        
        Raises:
            ValueError: If the API key is missing or invalid
            ConnectionError: If the connection to the API fails
        """
        # Get API key from environment
        self.api_key = os.getenv('GOOGLE_API_KEY')
        if not self.api_key or not isinstance(self.api_key, str):
            raise ValueError("GOOGLE_API_KEY not found in environment variables or invalid")
            
        try:
            genai.configure(api_key=self.api_key)
            
            # Available Gemini models (as of September 2025):
            # Text and Code Models:
            # - models/gemini-pro-latest           # Latest stable version
            # - models/gemini-2.5-pro             # Base model
            # - models/gemini-2.5-pro-preview-03-25  # Preview version
            # - models/gemini-2.5-flash           # Faster, lighter version
            # - models/gemini-2.5-flash-lite      # Most lightweight version
            # 
            # Embedding Models:
            # - models/embedding-001              # Latest stable embedding
            # - models/embedding-gecko-001        # Legacy embedding
            # - models/text-embedding-004         # Latest text embedding
            # - models/gemini-embedding-001       # Gemini-specific embedding
            #
            # Note: Model availability may change. Use list_available_models() to get current list.
            
            self.model = genai.GenerativeModel('gemini-2.5-flash')
            # Test connection with a simple prompt
            self.model.generate_content("Hello")
        except Exception as e:
            raise ConnectionError(f"Failed to connect to Gemini API: {str(e)}")

    def process_prompt(self, prompt: str, context: Optional[List[str]] = None) -> str:
        """
        Process a prompt using the Gemini API.

        Args:
            prompt (str): The prompt to process
            context (Optional[List[str]]): Optional list of code chunks to provide context
            
        Returns:
            str: The response generated by the model
            
        Raises:
            ValueError: If the question is empty
            Exception: For any other API call errors
        """
        if not prompt.strip():
            raise ValueError("Question cannot be empty")
            
        try:
            # Build prompt with context if provided
            completed_prompt = prompt
            if context:
                context_text = "\n".join(context)
                completed_prompt = f"Given this context:\n\n{context_text}\n\nQuestion: {prompt}"
            
            response = self.model.generate_content(
                completed_prompt,
                generation_config=self.generation_config
            )
            
            if not response.text:
                raise Exception("Empty response received from API")
                
            return response.text.strip()
            
        except Exception as e:
            error_msg = str(e)
            if "quota" in error_msg.lower():
                raise Exception("Gemini API quota exceeded. Please try again later.")
            elif "rate" in error_msg.lower():
                print(error_msg)
                raise Exception("Gemini API rate limit reached. Please try again in a few seconds.")
            else:
                raise Exception(f"Error calling Gemini API: {error_msg}")
    
    def get_embedding(self, text: str) -> List[float]:
        """
        Generate an embedding for the given text.
        
        Args:
            text (str): The text to generate an embedding for
            
        Returns:
            List[float]: The generated embedding
            
        Raises:
            ValueError: If text is empty
            Exception: For any API errors
        """
        if not text.strip():
            raise ValueError("Text cannot be empty")
            
        try:
            # Currently, Gemini doesn't have a direct embedding API
            # Using the model to generate a numeric representation
            prompt = f"""Analyze this text and generate a 128-dimensional embedding vector.
            Each dimension should be a float between -1 and 1.
            Text to analyze: {text}
            Output only the JSON array of numbers."""
            
            response = self.model.generate_content(
                prompt,
                generation_config={**self.generation_config, "temperature": 0.1}
            )
            
            if not response.text:
                raise Exception("Empty response received from API")
                
            try:
                # Try to parse the response as a list of floats
                embedding = json.loads(response.text.strip())
                if isinstance(embedding, list) and len(embedding) == 128:
                    return embedding
                else:
                    return [0.0] * 128  # Return zero vector if parsing fails
            except json.JSONDecodeError:
                return [0.0] * 128  # Return zero vector if JSON is invalid
                
        except Exception as e:
            error_msg = str(e)
            if "quota" in error_msg.lower():
                raise Exception("Gemini API quota exceeded. Please try again later.")
            elif "rate" in error_msg.lower():
                raise Exception("Gemini API rate limit reached. Please try again in a few seconds.")
            else:
                raise Exception(f"Error generating embedding: {error_msg}")
        
    def extract_metadata(self, code_chunk: str) -> Dict[str, Any]:
        """
        Extract metadata from a code chunk using Gemini's code understanding capabilities.
        
        Args:
            code_chunk (str): The code chunk to analyze
            
        Returns:
            Dict[str, Any]: The extracted metadata including functions, variables, etc.
            
        Raises:
            ValueError: If code_chunk is empty
            Exception: For any API errors
        """
        if not code_chunk.strip():
            raise ValueError("Code chunk cannot be empty")
            
        try:
            # Create a structured prompt for code analysis
            prompt = f"""Analyze this code chunk and extract metadata in JSON format:

{code_chunk}

Generate a JSON object containing:
1. Functions: List of function names with their parameters and return types
2. Variables: List of variable names and their types
3. Classes: List of class names and their methods
4. Dependencies: List of imports and dependencies
5. Documentation: Any docstrings or comments found

Output only valid JSON."""

            response = self.model.generate_content(
                prompt,
                generation_config={**self.generation_config, "temperature": 0.1}  # Lower temperature for more precise output
            )
            
            if not response.text:
                raise Exception("Empty response received from API")
            
            try:
                # Try to parse the response as JSON
                metadata = json.loads(response.text.strip())
                return metadata
            except json.JSONDecodeError:
                # If JSON parsing fails, return a basic structure
                return {
                    "functions": [],
                    "variables": [],
                    "classes": [],
                    "dependencies": [],
                    "documentation": []
                }
                
        except Exception as e:
            error_msg = str(e)
            if "quota" in error_msg.lower():
                raise Exception("Gemini API quota exceeded. Please try again later.")
            elif "rate" in error_msg.lower():
                raise Exception("Gemini API rate limit reached. Please try again in a few seconds.")
            else:
                raise Exception(f"Error extracting metadata: {error_msg}")
            
    def set_temperature(self, temperature: float) -> None:
        """
        Configure the temperature for text generation.
        
        Args:
            temperature (float): Value between 0 (more deterministic) and 1 (more creative)
            
        Raises:
            ValueError: If temperature is not between 0 and 1
        """
        if not 0 <= temperature <= 1:
            raise ValueError("Temperature must be between 0 and 1")
        self.generation_config["temperature"] = temperature
        
    def set_model(self, model_name: str) -> None:
        """
        Switch to a different Gemini model.
        
        Args:
            model_name (str): Name of the model to use. Can be either the short name
                            (e.g., 'gemini-pro-latest') or full name (e.g., 'models/gemini-pro-latest')
        
        Raises:
            ValueError: If the model is not available
            ConnectionError: If connection to the API fails
        """
        try:
            # Add 'models/' prefix if not present
            if not model_name.startswith('models/'):
                model_name = f'models/{model_name}'
            
            # Check if model is available
            available_models = self.list_available_models()
            if model_name not in available_models:
                raise ValueError(f"Model '{model_name}' not available. Available models: {', '.join(available_models)}")
            
            # Create new model instance
            self.model = genai.GenerativeModel(model_name)
            
            # Test the model
            self.model.generate_content("Test")
            
        except Exception as e:
            if "not available" in str(e):
                raise ValueError(str(e))
            raise ConnectionError(f"Failed to switch to model '{model_name}': {str(e)}")